version: 2
jobs:
  build:
    working_directory: ~/circleci-test-repo
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-docker-{{ .Branch }}
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true
      - run:
          name: git clone projects
          command: |
            git clone -b topic-build-health-check git@github.com:Nextremer/minarai-environment.git
            cd minarai-environment
            git clone git@github.com:Nextremer/minarai-daialogue-hub.git
            git clone git@github.com:Nextremer/minarai-connection-service.git
            git clone git@github.com:Nextremer/minarai-socketio-connector.git
            git clone git@github.com:Nextremer/minarai-websocket-connector.git
            git clone git@github.com:Nextremer/minarai-developer-console.git
            git clone git@github.com:Nextremer/minarai-application2.git
            git clone git@github.com:Nextremer/minarai-log-api.git
            git clone git@github.com:Nextremer/minarai-image-service.git
            git clone git@github.com:Nextremer/minarai-cs-chat-application.git
            git clone git@github.com:Nextremer/minarai-line-connector.git
            git clone git@github.com:Nextremer/minarai-botframework-connector.git
      - run:
          name: build and start
          command: |
            cd minarai-environment
            make start
            docker ps
            sleep 120
            curl http://localhost:3000
      - run:
          name: Save Docker layers cache
          command: |
            DOCKER_IMAGES=$(docker images --format "{{.Repository}}" --filter=reference="${CIRCLE_PROJECT_REPONAME}_*")
            DOCKER_LAYERS=$(for image in $DOCKER_IMAGES; do docker history $image -q | grep -v missing; done)
            docker save -o ~/docker-layers.tar $DOCKER_LAYERS
      - save_cache:
          key: v1-docker-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/docker-layers.tar
      - run:
          name: test
          command: |
            git clone git@github.com:Nextremer/minarai-ping-client.git
            cd minarai-ping-client
            npm install
            npm start

workflows:
  version: 2
  # commit:
  #   jobs:
  #     - test
  #     - deploy
  nightly:
    triggers:
      - schedule:
          cron: "52 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build